version: '3.4'

services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookiffy.Api
    build:
      context: .
      dockerfile: Bookify.API/Dockerfile
    depends_on:
     - bookify-db

  bookify-db:
    image: postgres
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
     - 5432:5432
